TAP_DANCE_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

WPM_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes

COMMAND_ENABLE   = no # Commands for debug and configuration
UNICODE_ENABLE   = no # Unicode
MOUSEKEY_ENABLE  = no # Mouse keys(+4700)

WPM_ENABLE = yes

SLEEP_LED_ENABLE  = no
NKRO_ENABLE	      = no
BACKLIGHT_ENABLE  = no
MIDI_ENABLE       = no
UNICODE_ENABLE    = no
BLUETOOTH_ENABLE  = no
AUDIO_ENABLE	  = no
FAUXCLICKY_ENABLE = no
HD44780_ENABLE    = no
BOOTMAGIC_ENABLE  = no
